/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resources.views;

import app.models.Hospede;
import app.controllers.HospedeController;
import config.Flash;
import java.sql.ResultSet;
import javax.script.ScriptException;

/**
 *
 * @author leonardo
 */
public class BuscarHospede extends javax.swing.JDialog {

    private final String redirectClass;
    private Hospede hospede;
    private HospedeController hospedeController;
    private ResultSet resultSet;
    private java.awt.Frame parent;

    /**
     * Creates new form BuscarHospede
     *
     * @param parent
     * @param modal
     * @param redirectClass
     */
    public BuscarHospede(java.awt.Frame parent, boolean modal, String redirectClass) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        this.setLocationRelativeTo(null);

        this.redirectClass = redirectClass;

        this.hospede = new Hospede();
        this.hospedeController = new HospedeController(this.hospede);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        tfBuscarHospede = new javax.swing.JFormattedTextField();
        btnSearchHospede = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));

        try {
            tfBuscarHospede.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfBuscarHospede.setText("");
        tfBuscarHospede.setToolTipText("");
        tfBuscarHospede.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        btnSearchHospede.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearchHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/png/btn-search.png"))); // NOI18N
        btnSearchHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchHospede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchHospedeMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/png/banners/buscar-hospede.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("Poppins", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(123, 123, 123));
        jLabel2.setText("Informe o cpf do hóspede");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(tfBuscarHospede))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchHospede)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tfBuscarHospede, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchHospedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchHospedeMouseClicked
        try {
            searchHospede();
        } catch (Exception ex) {
            System.out.println("Erro na função btnSearchHospedeMouseClicked(): " + ex);
        }
    }//GEN-LAST:event_btnSearchHospedeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSearchHospede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JFormattedTextField tfBuscarHospede;
    // End of variables declaration//GEN-END:variables

    public void searchHospede() throws Exception {
        String pesquisa = this.tfBuscarHospede.getText().trim();
        if (!pesquisa.equals("")) {
            this.resultSet = this.hospede.equals("cpf", pesquisa, null);
            if (this.resultSet.next()) {
                redirect();
            } else {
                Flash.warning("Nenhum hóspede encontrado.");
            }
        } else {
            Flash.warning("Digite o número de CPF do hóspede para iniciar a busca!");
        }
    }

    private void redirect() throws ScriptException {

        switch (this.redirectClass) {

            case "ContratarProduto": {
                this.dispose();
                ContratarProduto contratarProduto = new ContratarProduto(this.parent, true, this.resultSet);
                contratarProduto.setVisible(true);
                break;
            }

            case "ContratarServico": {
                this.dispose();
                ContratarServico contratarServico = new ContratarServico(this.parent, true, this.resultSet);
                contratarServico.setVisible(true);
                break;
            }

            case "DetalharContratoHospede": {
                this.dispose();
                ContratarProduto contratarProduto = new ContratarProduto(this.parent, true, this.resultSet);
                contratarProduto.setVisible(true);
                break;
            }

        }

    }

}
