/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resources.views.elementos;

import app.controllers.HospedeController;
import config.Carbon;
import config.Flash;
import config.Helper;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author leonardo
 */
public class EditarHospede extends javax.swing.JPanel {

    private int idHospedeSelecionado;

    private JTabbedPane tabbedPane;

    private ResultSet resultSet;
    private ResultSet sessaoHospede;

    private app.models.Hospede hospede;

    private HospedeController hospedeController;

    /**
     * Creates new form DetalheHospede
     */
    public EditarHospede(int id, JTabbedPane jp) {
        try {
            initComponents();
            this.idHospedeSelecionado = id;
            this.tabbedPane = jp;

            this.hospede = new app.models.Hospede();
            this.hospedeController = new HospedeController(this.hospede);

            this.sessaoHospede = this.hospede.find(this.idHospedeSelecionado);

            loadHospede();
        } catch (Exception ex) {
            System.out.println("Erro no construtor HospedeServicos(): " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnEditarHospede = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tfTelefone = new javax.swing.JFormattedTextField();
        tfNascimento = new javax.swing.JFormattedTextField();
        labelNascimento = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        labelEmaim = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        tfCpf = new javax.swing.JFormattedTextField();
        tfCelular = new javax.swing.JFormattedTextField();
        labelCelular = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tfLogradouro = new javax.swing.JTextField();
        tfComplemento = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        tfEstado = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        labelComplemento = new javax.swing.JLabel();
        labelLogradouro = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelCep = new javax.swing.JLabel();
        labelNumeroCasa = new javax.swing.JLabel();
        ajaxStatus = new javax.swing.JLabel();
        labelBairro = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        tfCep = new javax.swing.JTextField();
        tfNumeroCasa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tfCartaoCredito = new javax.swing.JFormattedTextField();
        tfCodigoSeguranca = new javax.swing.JFormattedTextField();
        tfDataVencimento = new javax.swing.JFormattedTextField();
        labelDataVencimento = new javax.swing.JLabel();
        labelCodigoSeguranca = new javax.swing.JLabel();
        labelCartaoCredito = new javax.swing.JLabel();
        rbVisa = new javax.swing.JRadioButton();
        rbElo = new javax.swing.JRadioButton();
        rbDinersClub = new javax.swing.JRadioButton();
        rbMastercard = new javax.swing.JRadioButton();
        rbAmericanExpress = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        tfDataFinalContrato = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tfDataInicialContrato = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));

        btnEditarHospede.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditarHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/png/botoes/editar-hospede.png"))); // NOI18N
        btnEditarHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarHospede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarHospedeMouseClicked(evt);
            }
        });

        btnVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/png/botoes/fechar.png"))); // NOI18N
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        try {
            tfNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfNascimento.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        labelNascimento.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelNascimento.setText("* Nascimento:");

        tfEmail.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        tfNome.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        labelEmaim.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelEmaim.setText("* E-mail:");

        labelNome.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNome.setText("* Nome:");

        labelCpf.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelCpf.setText("* CPF:");

        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCpf.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        try {
            tfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCelular.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        tfCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCelularActionPerformed(evt);
            }
        });

        labelCelular.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelCelular.setText("Celular:");

        labelTelefone.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelTelefone.setText("Telefone:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmaim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmaim, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfCelular, tfCpf, tfEmail, tfNascimento, tfNome, tfTelefone});

        jTabbedPane1.addTab("Dados Pessoais", jPanel1);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        tfLogradouro.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        tfComplemento.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        tfCidade.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        tfEstado.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        labelCidade.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelCidade.setText("* Cidade:");

        labelComplemento.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelComplemento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelComplemento.setText("Complemento:");

        labelLogradouro.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelLogradouro.setText("* Logradouro:");

        labelEstado.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelEstado.setText("* Estado:");

        labelCep.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelCep.setText("* CEP:");

        labelNumeroCasa.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelNumeroCasa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNumeroCasa.setText("* Número:");

        ajaxStatus.setFont(new java.awt.Font("Poppins", 2, 12)); // NOI18N

        labelBairro.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelBairro.setText("* Bairro:");

        tfBairro.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        tfCep.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        tfCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCepKeyReleased(evt);
            }
        });

        tfNumeroCasa.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(256, 256, 256)
                            .addComponent(labelCep, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ajaxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(labelLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(labelComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfComplemento))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(labelNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCep, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajaxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfBairro, tfCep, tfCidade, tfComplemento, tfEstado, tfLogradouro, tfNumeroCasa});

        jTabbedPane1.addTab("Localização", jPanel2);

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));

        try {
            tfCartaoCredito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCartaoCredito.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        try {
            tfCodigoSeguranca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCodigoSeguranca.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        try {
            tfDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataVencimento.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        labelDataVencimento.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelDataVencimento.setText("Data Vencimento:");

        labelCodigoSeguranca.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelCodigoSeguranca.setText("Código Segurança:");

        labelCartaoCredito.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labelCartaoCredito.setText("Cartão Crédito:");

        rbVisa.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbVisa);
        rbVisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rbVisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbVisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbVisa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbVisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/png/card-5.png"))); // NOI18N
        rbVisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbVisaMouseClicked(evt);
            }
        });

        rbElo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbElo);
        rbElo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rbElo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbElo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbElo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbElo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/png/card-3.png"))); // NOI18N
        rbElo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbEloMouseClicked(evt);
            }
        });

        rbDinersClub.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbDinersClub);
        rbDinersClub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rbDinersClub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbDinersClub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbDinersClub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbDinersClub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/png/card-2.png"))); // NOI18N
        rbDinersClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDinersClubMouseClicked(evt);
            }
        });

        rbMastercard.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbMastercard);
        rbMastercard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rbMastercard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbMastercard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbMastercard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbMastercard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/png/card-4.png"))); // NOI18N
        rbMastercard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMastercardMouseClicked(evt);
            }
        });

        rbAmericanExpress.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbAmericanExpress);
        rbAmericanExpress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rbAmericanExpress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbAmericanExpress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbAmericanExpress.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbAmericanExpress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/png/card-1.png"))); // NOI18N
        rbAmericanExpress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAmericanExpressMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbAmericanExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbDinersClub)
                        .addGap(18, 18, 18)
                        .addComponent(rbElo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(rbMastercard, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(rbVisa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDataVencimento)
                            .addComponent(labelCodigoSeguranca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCodigoSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(labelCartaoCredito)
                        .addGap(18, 18, 18)
                        .addComponent(tfCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbAmericanExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbDinersClub)
                            .addComponent(rbElo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMastercard, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbVisa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCartaoCredito)
                            .addComponent(tfCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodigoSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCodigoSeguranca))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDataVencimento)
                            .addComponent(tfDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfCartaoCredito, tfCodigoSeguranca, tfDataVencimento});

        jTabbedPane1.addTab("Dados de Pagamento", jPanel3);

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));

        try {
            tfDataFinalContrato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataFinalContrato.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel9.setText("Data Final do Contrato:");

        tfDataInicialContrato.setEditable(false);
        try {
            tfDataInicialContrato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataInicialContrato.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel6.setText("Data de Inicio do Contrato:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDataFinalContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataInicialContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataInicialContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataFinalContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contrato", jPanel4);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Hóspede");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarHospede)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltar)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditarHospede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarHospedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarHospedeMouseClicked
        if (isValidForm()) {
            try {
                this.hospedeController.update(this.requestInputs(), this.idHospedeSelecionado);
            } catch (SQLException ex) {
                System.out.println("Erro na função requestInputs(), em EditarHospede()"+ex);
            }
        }
    }//GEN-LAST:event_btnEditarHospedeMouseClicked

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        closeJPanel();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void tfCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCelularActionPerformed

    private void tfCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCepKeyReleased
        this.hospede.loadWebService(new JTextField[]{
            tfCpf, tfLogradouro, tfCidade, tfEstado, tfBairro
        }, ajaxStatus);
    }//GEN-LAST:event_tfCepKeyReleased

    private void rbVisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbVisaMouseClicked
        this.hospede.cardsRadioButtons(new JRadioButton[]{
            rbAmericanExpress, rbDinersClub, rbElo, rbMastercard, rbVisa
        });
    }//GEN-LAST:event_rbVisaMouseClicked

    private void rbEloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbEloMouseClicked
        this.hospede.cardsRadioButtons(new JRadioButton[]{
            rbAmericanExpress, rbDinersClub, rbElo, rbMastercard, rbVisa
        });
    }//GEN-LAST:event_rbEloMouseClicked

    private void rbDinersClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDinersClubMouseClicked
        this.hospede.cardsRadioButtons(new JRadioButton[]{
            rbAmericanExpress, rbDinersClub, rbElo, rbMastercard, rbVisa
        });
    }//GEN-LAST:event_rbDinersClubMouseClicked

    private void rbMastercardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMastercardMouseClicked
        this.hospede.cardsRadioButtons(new JRadioButton[]{
            rbAmericanExpress, rbDinersClub, rbElo, rbMastercard, rbVisa
        });
    }//GEN-LAST:event_rbMastercardMouseClicked

    private void rbAmericanExpressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAmericanExpressMouseClicked
        this.hospede.cardsRadioButtons(new JRadioButton[]{
            rbAmericanExpress, rbDinersClub, rbElo, rbMastercard, rbVisa
        });
    }//GEN-LAST:event_rbAmericanExpressMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajaxStatus;
    private javax.swing.JLabel btnEditarHospede;
    private javax.swing.JLabel btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCartaoCredito;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelCep;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCodigoSeguranca;
    private javax.swing.JLabel labelComplemento;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDataVencimento;
    private javax.swing.JLabel labelEmaim;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelLogradouro;
    private javax.swing.JLabel labelNascimento;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumeroCasa;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JRadioButton rbAmericanExpress;
    private javax.swing.JRadioButton rbDinersClub;
    private javax.swing.JRadioButton rbElo;
    private javax.swing.JRadioButton rbMastercard;
    private javax.swing.JRadioButton rbVisa;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfCartaoCredito;
    private javax.swing.JFormattedTextField tfCelular;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JFormattedTextField tfCodigoSeguranca;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JFormattedTextField tfDataFinalContrato;
    private javax.swing.JFormattedTextField tfDataInicialContrato;
    private javax.swing.JFormattedTextField tfDataVencimento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEstado;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JFormattedTextField tfNascimento;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumeroCasa;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

    private void closeJPanel() {
        this.tabbedPane.setSelectedIndex(1);
        this.tabbedPane.removeTabAt(this.tabbedPane.getTabCount() - 1);
    }

    private boolean isValidForm() {
        return (this.hospede.setNome(tfNome.getText())
                && this.hospede.setEmail(tfEmail.getText())
                && this.hospede.setCpf(tfCpf.getText())
                && this.hospede.setNascimento(tfNascimento.getText())
                && this.hospede.setCep(tfCep.getText())
                && this.hospede.setLogradouro(tfLogradouro.getText())
                && this.hospede.setNumero(tfNumeroCasa.getText())
                && this.hospede.setBairro(tfBairro.getText())
                && this.hospede.setCidade(tfCidade.getText())
                && this.hospede.setEstado(tfEstado.getText())
                && this.hospede.setContato(tfTelefone.getText(), tfCelular.getText())
                && (this.hospede.setTipoCartao(
                        rbAmericanExpress.isSelected(),
                        rbDinersClub.isSelected(),
                        rbElo.isSelected(),
                        rbMastercard.isSelected(),
                        rbVisa.isSelected()
                ))
                && this.hospede.setCartaoCredito(tfCartaoCredito.getText())
                && this.hospede.setDataVencimento(tfDataVencimento.getText())
                && this.hospede.setCodigoSeguranca(tfCodigoSeguranca.getText()));
    }

    private void loadHospede() {
        try {
            buttonGroup1.clearSelection();

            if (this.sessaoHospede.next()) {
                tfNome.setText(this.sessaoHospede.getString("nome"));
                tfEmail.setText(this.sessaoHospede.getString("email"));
                tfCpf.setText(this.sessaoHospede.getString("cpf"));
                tfNascimento.setText(Carbon.getDate(this.sessaoHospede.getDate("nascimento"), "dd/MM/yyyy"));
                tfCep.setText(this.sessaoHospede.getString("cep"));
                tfLogradouro.setText(this.sessaoHospede.getString("logradouro"));
                tfNumeroCasa.setText(this.sessaoHospede.getString("numero"));
                tfComplemento.setText(this.sessaoHospede.getString("complemento"));
                tfBairro.setText(this.sessaoHospede.getString("bairro"));
                tfCidade.setText(this.sessaoHospede.getString("cidade"));
                tfEstado.setText(this.sessaoHospede.getString("estado"));
                tfTelefone.setText(this.sessaoHospede.getString("telefone"));
                tfCelular.setText(this.sessaoHospede.getString("celular"));
                tfDataInicialContrato.setText(Carbon.getDate(this.sessaoHospede.getDate("data_inicial"), "dd/MM/yyyy"));
                tfDataFinalContrato.setText(Carbon.getDate(this.sessaoHospede.getDate("data_final"), "dd/MM/yyyy"));
                setCardsRadioButtons(this.sessaoHospede.getInt("tipo_cartao"));
                tfCartaoCredito.setText(this.sessaoHospede.getString("cartao_credito"));
                tfDataVencimento.setText(Carbon.getDate(this.sessaoHospede.getDate("data_vencimento"), "dd/MM/yyyy"));
                tfCodigoSeguranca.setText(this.sessaoHospede.getString("codigo_seguranca"));
                // status_contrato
            } else {
                Flash.error("Erro na exibição nos dados do hóspede");
                closeJPanel();
            }
        } catch (SQLException ex) {
            System.out.println("Erro na função loadHospede(): " + ex);
        }
    }
    
    public void setCardsRadioButtons(int selected){
        if(selected == 1) rbAmericanExpress.setSelected(true);
        if(selected == 2) rbDinersClub.setSelected(true);
        if(selected == 3) rbElo.setSelected(true); 
        if(selected == 4) rbMastercard.setSelected(true);
        if(selected == 5) rbVisa.setSelected(true);
        this.hospede.cardsRadioButtons(new JRadioButton[]{
            rbAmericanExpress, rbDinersClub, rbElo, rbMastercard, rbVisa
        });
    }

    public Object[] requestInputs() throws SQLException {
        return new Object[]{
            tfNome.getText().toUpperCase().trim(),
            tfEmail.getText().toUpperCase().trim(),
            tfCpf.getText().toUpperCase().trim(),
            Carbon.dateToDB(Helper.explode("/", tfNascimento.getText())),
            tfCep.getText().toUpperCase().trim(),
            tfLogradouro.getText().toUpperCase().trim(),
            tfNumeroCasa.getText().toUpperCase().trim(),
            tfComplemento.getText().toUpperCase().trim(),
            tfBairro.getText().toUpperCase().trim(),
            tfCidade.getText().toUpperCase().trim(),
            tfEstado.getText().toUpperCase().trim(),
            tfTelefone.getText().toUpperCase().trim(),
            tfCelular.getText().toUpperCase().trim(),
            this.sessaoHospede.getString("data_inicial"),
            Carbon.dateToDB(Helper.explode("/", tfDataFinalContrato.getText())),
            this.hospede.getTipoCartao(rbAmericanExpress.isSelected(), rbDinersClub.isSelected(), rbElo.isSelected(), rbMastercard.isSelected()),
            tfCartaoCredito.getText().trim(),
            Carbon.dateToDB(Helper.explode("/", tfDataVencimento.getText())),
            tfCodigoSeguranca.getText().trim(),
            this.sessaoHospede.getString("status_contrato"),
        };
    }

}
